/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    ICustomAaa: typeof import('~icons/custom/aaa')['default']
    ICustomLine_dancing: typeof import('~icons/custom/line_dancing')['default']
    NButton: typeof import('naive-ui')['NButton']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NText: typeof import('naive-ui')['NText']
    NTree: typeof import('naive-ui')['NTree']
    StreamerBorder: typeof import('./../src/components/autoImport/StreamerBorder.vue')['default']
  }
}
