/*
 * @Author       : peter peter@qingcongai.com
 * @Date         : 2024-11-25 09:08:35
 * @LastEditors  : peter peter@qingcongai.com
 * @LastEditTime : 2024-11-26 17:55:15
 * @Description  :
 */
/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CForm: typeof import('./../src/components/autoImport/CForm.vue')['default']
    CInput: typeof import('./../src/components/autoImport/CInput.vue')['default']
    FenceWrapper: typeof import('./../.vitepress/theme/components/autoImport/FenceWrapper.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    ICustomAaa: typeof import('~icons/custom/aaa')['default']
    'ILineMd:playFilled': typeof import('~icons/line-md/play-filled')['default']
    'IMaterialSymbols:contentCopyOutline': typeof import('~icons/material-symbols/content-copy-outline')['default']
    NA: typeof import('naive-ui')['NA']
    NAlert: typeof import('naive-ui')['NAlert']
    NBlockquote: typeof import('naive-ui')['NBlockquote']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NP: typeof import('naive-ui')['NP']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NTable: typeof import('naive-ui')['NTable']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NTree: typeof import('naive-ui')['NTree']
  }
}
