name: pnpm 安装和缓存
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: branches-main
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@main
      - name: 安装 pnpm
        uses: pnpm/action-setup@master
        with:
          version: 9
      - name: 使用 node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: 安装依赖
        run: pnpm install
        shell: bash
      - name: 构建
        run: pnpm build
        shell: bash
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
          name: github-pages
      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
        id: deployment
