name: pnpm 安装和缓存
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@main
      - name: 安装 pnpm
        uses: pnpm/action-setup@master
        with:
          version: 9
      - name: 使用 node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: 安装依赖
        run: pnpm install
